using PlayerRoles.FirstPersonControl;
using PlayerRoles;
using UnityEngine;

namespace UserSettings.ServerSpecific.Examples
{
	/// <summary>
	/// Provides an example implementation of text areas in server-specific setttings.
	/// <para /> This example makes use of auto-generated IDs, instead of recommended enum identifiers. This is fine since we aren't saving any settings on the client.
	/// </summary>
	public class SSTextAreaExample : SSExampleImplementationBase
	{
		/// <inheritdoc />
		public override string Name => "Different types of Text Areas";

		private const string DemoSingleLine = "This is a single-line text area.";
		private const string DemoRichText = "<color=green>This</color> <size=30>text</size> <color=red>area</color> <u>supports</u> <i>Rich</i> <b>Text</b> <rotate=\"25\">Tags</rotate>.";
		private const string DemoMultiLineCustomText = "This is a multi-line text area which is collapsed by default. It can be expanded, retaining its previous state when toggling this tab on and off. As you probably noticed, it also features a custom text while collapsed.\n\nYou can use the newline symbol (or \"<noparse><br></noparse>\") to create\nnew\nlines\nwithout\nrestrictions. \n\nRich Text Tags are still supported, but due to technical limitations, links only work on non-collapsable text areas.\n\nDifferent writing systems are also supported:\nA B C D   А Б В Г    Α Β Γ Δ    أ ب ت ث   א ב ג ד   山 水 火 木   あ い う え   가 나 다 라";
		private const string DemoMultiLineAutoGenerated = "This is another multi-line text area, but this one features auto-generated preview text when collapsed, with ellipses appearing when the text no longer fits. It also has an option enabled to collapse automatically when you switch off this settings tab. In other words, you will need to re-expand this text area each time you visit this tab.";
		private const string DemoExtendedByDefault = "This multi-line text area is expanded by default but can be collapsed if needed. It will retain its previous state when toggling this tab on and off.";
		private const string DemoExtendedEveryTime = "This multi-line text area is similar to the one above, but it will re-expand itself after collapsing each time you visit this tab.";
		private const string DemoExtendedPermanent = "This multi-line text area cannot be collapsed.\nIt remains fully expanded at all times, but supports URL links.\nExample link: <link=\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\"><mark=#5865f215>[Click]</mark></link>";

		private SSButton _requestScanButton;
		private SSTextArea _responseScan;

		/// <inheritdoc />
		public override void Activate()
		{
			ServerSpecificSettingsSync.DefinedSettings = new ServerSpecificSettingBase[]
			{
				new SSGroupHeader("Different Text Area Types"),
				new SSTextArea(null, DemoSingleLine),
				new SSTextArea(null, DemoRichText),
				new SSTextArea(null, DemoMultiLineCustomText, foldoutMode: SSTextArea.FoldoutMode.CollapsedByDefault, "Expand me!"),
				new SSTextArea(null, DemoMultiLineAutoGenerated, foldoutMode: SSTextArea.FoldoutMode.CollapseOnEntry),
				new SSTextArea(null, DemoExtendedByDefault, foldoutMode: SSTextArea.FoldoutMode.ExtendedByDefault),
				new SSTextArea(null, DemoExtendedEveryTime, foldoutMode: SSTextArea.FoldoutMode.ExtendOnEntry),
				new SSTextArea(null, DemoExtendedPermanent, foldoutMode: SSTextArea.FoldoutMode.NotCollapsable),

				new SSGroupHeader("Human Scanner", hint: "Generates a list of alive humans with their distances to you. The size is automatically adjusted based on the number of results."),
				_responseScan = new SSTextArea(null, "Not scanned yet"), // Store in variable for easier reference.
				_requestScanButton = new SSButton(null, "Scan for players", "Scan")
			};

			ServerSpecificSettingsSync.ServerOnSettingValueReceived += ServerOnSettingValueReceived;
			ServerSpecificSettingsSync.SendToAll();
		}

		/// <inheritdoc />
		public override void Deactivate()
		{
			ServerSpecificSettingsSync.ServerOnSettingValueReceived -= ServerOnSettingValueReceived;
		}

		private void ServerOnSettingValueReceived(ReferenceHub sender, ServerSpecificSettingBase modifiedSetting)
		{
			if (modifiedSetting.SettingId != _requestScanButton.SettingId)
				return;

			OnScannerButtonPressed(sender);
		}

		private void OnScannerButtonPressed(ReferenceHub sender)
		{
			if (sender.roleManager.CurrentRole is not IFpcRole senderFpc)
			{
				_responseScan.SendTextUpdate("Your current role is not supported.", false, x => x == sender);
				return;
			}

			string response = null;

			foreach (ReferenceHub hub in ReferenceHub.AllHubs)
			{
				if (hub.roleManager.CurrentRole is not HumanRole human)
					continue;

				if (hub == sender)
					continue;

				float distance = Vector3.Distance(human.FpcModule.Position, senderFpc.FpcModule.Position);
				string line = $"\n-{hub.nicknameSync.DisplayName} ({human.GetColoredName()}) - {distance} m";

				response ??= "Detected humans: ";
				response += line;
			}

			_responseScan.SendTextUpdate(response ?? "No humans detected.", false, x => x == sender);
		}
	}
}
